mystring='nitin 77 1212hers'
print(len(mystring))
print(mystring.strip())
print(mystring.lower())
print(mystring.upper())
print(mystring.replace("hers","nick"))
print(mystring.capitalize())
print(mystring.title())
print(mystring.count("a"))
print(mystring.endswith("7"))
print(mystring.startswith("n"))
print(mystring.find("77"))
print(mystring.index("7"))
print(mystring.islower())
print(mystring.isupper())
print(mystring.isalnum())
print(mystring.isalpha())